feat: reimplement in bash script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -16,51 +16,37 @@ runs:
       role-to-assume: arn:aws:iam::779099367007:role/github-actions-storage
 
   - name: Download assets
-    uses: actions/github-script@v5
+    shell: bash
     env:
       AWS_ACCESS_KEY_ID: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
       AWS_SECRET_ACCESS_KEY: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
       AWS_SESSION_TOKEN: ${{ steps.aws-credentials.outputs.aws-session-token }}
       ASSETS_NAME: ${{ inputs.name }}
       ASSETS_BASE_PATH: assets/${{ steps.aws-credentials.outputs.subject }}/run:${{ env.GITHUB_RUN_ID }}/attempt:${{ env.GITHUB_RUN_ATTEMPT }}
-    with:
-      script: |
-        const proc = require('child_process')
+      BUCKET: incognia-github-actions-storage
+    run: |
+      function objectPath {
+        printf "%s" "${ASSETS_BASE_PATH}/$1"
+      }
 
-        const env = process.env
-        const BUCKET = 'incognia-github-actions-storage'
+      function s3ObjectUrl {
+        printf "%s" "s3://${BUCKET}/$(objectPath $1)"
+      }
 
-        function objectPath(key) {
-          return `${env.ASSETS_BASE_PATH}/${key}`
-        }
+      function s3ObjectExists {
+        local object=$(objectPath $1)
+        aws s3api list-objects-v2 --bucket "${BUCKET}" --prefix "${object}" \
+          | jq --exit-status ".Contents[0] | .Key == \"${object}\"" >/dev/null
+      }
 
-        function s3ObjectUrl(key) {
-          return `s3://${BUCKET}/${objectPath(key)}`
-        }
+      echo "Checking if assets exist..."
 
-        function exec(command) {
-          proc.execSync(command, { shell: '/bin/bash', stdio: 'inherit' })
-        }
+      if ! s3ObjectExists ${ASSETS_NAME}
+      then
+        echo "Assets not found!"
+        echo "::error ::Assets not found!"
+        exit 1
+      fi
 
-        function execv(command) {
-          return proc.execSync(command, { shell: '/bin/bash', stdio: ['inherit', 'pipe', 'inherit'] })
-            .toString()
-            .trim()
-        }
-
-        async function s3ObjectExists(key) {
-          const object = objectPath(key)
-          const ret = execv(`
-            aws s3api list-objects-v2 --bucket "${BUCKET}" --prefix "${object}" \
-              | jq '.Contents[0] | .Key == "${object}"'
-          `)
-          return ret === 'true'
-        }
-
-        if (!await s3ObjectExists(env.ASSETS_NAME)) {
-          core.setFailed('Assets not found!')
-          return
-        }
-
-        core.info('Downloading assets...')
-        exec(`aws s3 cp "${s3ObjectUrl(env.ASSETS_NAME)}" - | tar -xvPf - -C /`)
+      echo "Downloading assets..."
+      aws s3 cp "$(s3ObjectUrl ${ASSETS_NAME})" - | tar -xvf -
